[build]
  functions = "functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "OPTIONS, POST"
    Access-Control-Allow-Headers = "Content-Type"
