[[headers]]
for = "/.netlify/functions/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://www.wevierart.com"   # or "*" for testing
  Access-Control-Allow-Methods = "POST,OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"
