[build]
  functions = "functions"
  
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.wevierart.com"
    Access-Control-Allow-Methods = "OPTIONS, POST"
    Access-Control-Allow-Headers = "Content-Type"
